// Basic Game Template - Generated by SNIB AI
const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');

// Game state
const game = {
    player: {
        x: 50,
        y: canvas.height - 60,
        width: 40,
        height: 40,
        color: '#00ff00',
        velocityY: 0,
        jumping: false
    },
    gravity: 0.5,
    jumpPower: -12,
    keys: {}
};

// Input handling
document.addEventListener('keydown', (e) => {
    game.keys[e.key] = true;
});

document.addEventListener('keyup', (e) => {
    game.keys[e.key] = false;
});

// Game functions
function update() {
    // Player movement
    if (game.keys['ArrowLeft'] && game.player.x > 0) {
        game.player.x -= 5;
    }
    if (game.keys['ArrowRight'] && game.player.x < canvas.width - game.player.width) {
        game.player.x += 5;
    }
    
    // Jumping
    if (game.keys[' '] && !game.player.jumping) {
        game.player.velocityY = game.jumpPower;
        game.player.jumping = true;
    }
    
    // Apply gravity
    game.player.velocityY += game.gravity;
    game.player.y += game.player.velocityY;
    
    // Ground collision
    if (game.player.y > canvas.height - game.player.height) {
        game.player.y = canvas.height - game.player.height;
        game.player.velocityY = 0;
        game.player.jumping = false;
    }
}

function draw() {
    // Clear canvas
    ctx.fillStyle = '#000';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Draw player
    ctx.fillStyle = game.player.color;
    ctx.fillRect(game.player.x, game.player.y, game.player.width, game.player.height);
    
    // Draw instructions
    ctx.fillStyle = '#fff';
    ctx.font = '16px Arial';
    ctx.fillText('Use Arrow Keys to move, Space to jump', 10, 30);
}

function gameLoop() {
    update();
    draw();
    requestAnimationFrame(gameLoop);
}

// Start the game
console.log('🎮 Basic game started! Use Arrow Keys and Space to play.');
gameLoop();